### ISSUE TITLE
Query regarding "IS_INDELIBLE_COMPATIBLE" field

### ISSUE THREAD

**Issue by jaspreetishar** [angtft/RAxMLGrove#2]
Dear Developers,
I'm Jaspreet, a Master's student at Tel Aviv University, Israel.

I am highly interested in using the RAxML Grove database to find suitable trees for my project. I need at least 50 trees having DNA sequence data with number of taxa >= 500 and overall number of alignment sites >= 1500. I am particularly curious about the field "IS_INDELIBLE_COMPATIBLE".

Since I'm also working with INDELible, setting this field as "1" yields only 7 trees, and setting it as "0" gives me 728 trees. Likewise, I was wondering what exactly does this field mean - why is a tree deemed "incompatible" with INDELible? If you could please provide some explanation behind this, it would be really helpful.

Awaiting your response, many thanks!
Best regards,
Jaspreet

**Comment by angtft** [comment]
Dear Jaspreet, 

INDELible seems to have a problem reading newick trees which use the E notation for small branch lengths. So if such branch lengths are present, we set IS_INDELIBLE_COMPATIBLE to 0.

Kind regards,
angtft

**Comment by jaspreetishar** [comment]
Thank you @angtft for your prompt and helpful response!

Best,
Jaspreet
