### ISSUE TITLE
Request for Sequence Data

### ISSUE THREAD

**Issue by jaspreetishar** [angtft/RAxMLGrove#3]
Dear Developers, 

The project that I'm working on requires the use of sequence data - which is not provided in the RAxML Grove database. For this reason, I wanted to request for sequence data of at least 50 trees (each with number of taxa >= 500, number of positions >= 1500, data type = DNA). 

Please let me know if providing this data would be possible, many thanks! 

Best regards, 
Jaspreet

**Comment by angtft** [comment]
Dear Jaspreet, 

unfortunately, it is not possible to provide the sequence data (to protect unpublished work of the web server users). 

Kind regards,
angtft

**Comment by jaspreetishar** [comment]
I understand, thank you for getting back to me.

Best,
Jaspreet
